# Site settings
title: Pretty Much All of the Time.
email: rossgeesman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lives in Seoul and sometimes makes messes in Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rossgeesman.github.io" # the base hostname & protocol for your site
twitter_username: rossgeesman
github_username:  rossgeesman

# Build settings
markdown: kramdown
